// <auto-generated />
using FerryBookingMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FerryBookingMVC.Migrations
{
    [DbContext(typeof(FerryContext))]
    [Migration("20240515141021_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FerryBookingClassLibrary.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FerryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FerryId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FerryId = 1
                        },
                        new
                        {
                            Id = 2,
                            FerryId = 1
                        },
                        new
                        {
                            Id = 3,
                            FerryId = 2
                        },
                        new
                        {
                            Id = 4,
                            FerryId = 2
                        });
                });

            modelBuilder.Entity("FerryBookingClassLibrary.Models.Ferry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CarPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GuestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxCars")
                        .HasColumnType("int");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ferries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarPrice = 197m,
                            GuestPrice = 99m,
                            MaxCars = 100,
                            MaxGuests = 50
                        },
                        new
                        {
                            Id = 2,
                            CarPrice = 197m,
                            GuestPrice = 99m,
                            MaxCars = 120,
                            MaxGuests = 60
                        });
                });

            modelBuilder.Entity("FerryBookingClassLibrary.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("FerryId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("FerryId");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            FerryId = 1,
                            Gender = "Female",
                            Name = "Alice Smith"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 1,
                            FerryId = 1,
                            Gender = "Male",
                            Name = "Bob Johnson"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 2,
                            FerryId = 1,
                            Gender = "Male",
                            Name = "Charlie Brown"
                        },
                        new
                        {
                            Id = 4,
                            CarId = 2,
                            FerryId = 1,
                            Gender = "Female",
                            Name = "Diana Prince"
                        },
                        new
                        {
                            Id = 5,
                            CarId = 3,
                            FerryId = 2,
                            Gender = "Female",
                            Name = "Eve Davis"
                        },
                        new
                        {
                            Id = 6,
                            CarId = 3,
                            FerryId = 2,
                            Gender = "Male",
                            Name = "Frank Miller"
                        },
                        new
                        {
                            Id = 7,
                            CarId = 4,
                            FerryId = 2,
                            Gender = "Female",
                            Name = "Grace Lee"
                        },
                        new
                        {
                            Id = 8,
                            CarId = 4,
                            FerryId = 2,
                            Gender = "Male",
                            Name = "Hank Green"
                        });
                });

            modelBuilder.Entity("FerryBookingClassLibrary.Models.Car", b =>
                {
                    b.HasOne("FerryBookingClassLibrary.Models.Ferry", null)
                        .WithMany("Cars")
                        .HasForeignKey("FerryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FerryBookingClassLibrary.Models.Guest", b =>
                {
                    b.HasOne("FerryBookingClassLibrary.Models.Car", null)
                        .WithMany("Guests")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FerryBookingClassLibrary.Models.Ferry", null)
                        .WithMany("Guests")
                        .HasForeignKey("FerryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FerryBookingClassLibrary.Models.Car", b =>
                {
                    b.Navigation("Guests");
                });

            modelBuilder.Entity("FerryBookingClassLibrary.Models.Ferry", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Guests");
                });
#pragma warning restore 612, 618
        }
    }
}
